✅ Add basic Revue tests
TryGhost/migrate pull request #164
Opened 2020-09-29 11:58 UTC by PaulAdamDavis

no issue

The data Revue returns via their API is pretty simple, so these tests are simple.

Covers the a basic post, addPrimaryTag, email, and pubName

2020-10-04 22:36 UTC, aileen requested changes
Beside my note, it would be cool, if we'd test the removal of UTM properties in links, as done [here](https://github.com/TryGhost/migrate/blob/master/packages/mg-revue-api/lib/processor.js#L9) and also twitter and youtube embeds, as we process [here](https://github.com/TryGhost/migrate/blob/master/packages/mg-revue-api/lib/processor.js#L130-L149)

2020-10-04 22:36 UTC, aileen commented on packages/mg-revue-api/test/processor.test.js
> +        data.slug.should.eql('https://www.getrevue.co/profile/sampleuser/issues/weekly-newsletter-of-sampleuser-issue-1-123456');
I think `slug` should not include the whole URL, that's why we try to remove it [here](https://github.com/TryGhost/migrate/blob/master/packages/mg-revue-api/lib/processor.js#L180) with regex. Can you check that again?

2020-10-07 08:13 UTC, PaulAdamDavis commented
Updated to test Twitter & YouTube embeds, and removal UTM properties.

2020-10-07 21:24 UTC, aileen approved these changes
Awesome stuff!

2020-10-07 21:24 UTC, merged